# Generated by Django 5.2.3 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='users/default.jpg', upload_to='users/'),
        ),
    ]
