# Generated by Django 5.2.3 on 2025-07-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='categoy_category_sort',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_sort_order',
        ),
    ]
